### ISSUE TITLE
GCP deployment middleware not working

### ISSUE THREAD

**Issue by kordless** [lucidworks/streams#1]
middleware is throwing a 500 error to the UI javascript when trying to do a user ID lookup. not sure what is wrong.

**Comment by kordless** [comment]
This file: `apps/jetty/api/webapps/api-extra-classpath.txt` does not contain `twitter4j`. 

Adding `apps/libs/twitter4j-core-4.0.4.jar` to the end of that file and restarting fixes this problem.

Investigate and update the build process to address this.

**Comment by erikhatcher** [comment]
I think this one should be fixed up now.   Had a work-in-progress in there to not alter the live file at first, but had not completed that "thought", oops.

**Comment by erikhatcher** [comment]
Fixed in https://github.com/lucidworks/streams/commit/272faaf8d10b6cc26179cfb5574b5595c4a4436a
