### ISSUE TITLE
Define global config

### ISSUE THREAD

**Issue by erikhatcher** [lucidworks/streams#13]
this is being left up to WordPress/marketing for the time being

**Comment by erikhatcher** [comment]
There will still be an admin interface to "create a button-ified app" that will store the info.

**Comment by kordless** [comment]
Workflow for creating an app is somewhat reasonable at this point:

- create application template using admin UI in buttons project pages
- create a new application in Fusion, then download the .zip file
- create a start script (referencing the eventual sample app in #15 to do so)
- tar cvfz sample-buttons.tgz * in the directory where the app was downloaded
- upload sample-buttons.tgz to the bucket on GCP
