### ISSUE TITLE
Produce sample application

### ISSUE THREAD

**Issue by erikhatcher** [lucidworks/streams#15]
end-to-end "Hello (Buttons) World" app, living in github.

**Comment by erikhatcher** [comment]
sample app needs to support authentication/login and an example settings page (like Sockitter once did for entering config keys).

**Comment by kordless** [comment]
Sorta done, but we really need to get the Appkit stuff working and build the application to publish. Not sure if that's us or someone else like @JoshEllinger at this point.

**Comment by kordless** [comment]
Per #14, Apps need to define their configuration, including: app name, source repo, required/supported Fusion version(s), cloud instance type, list of metadata that needs to be specified by the user (passwords for services, etc - like Sockitter's Twitter and Google Vision keys)

**Comment by kordless** [comment]
A couple of sample apps are now up for use by others.
