### ISSUE TITLE
Build continuous integration flow

### ISSUE THREAD

**Issue by erikhatcher** [lucidworks/streams#16]
Using our CI server, produce build process template/example that produces and delivers artifacts to be deployed.

**Comment by erikhatcher** [comment]
Should each project/app define the build process fully to handle app-specific challenges?   Or a global sort of build process that all projects will use?   Are we mandating app code directory structure and conventions?

**Comment by kordless** [comment]
This is related to the workflow around building apps and publishing them on a regular basis to the system to allow others to launch demos.

**Comment by erikhatcher** [comment]
@MarcusSorealheis maybe we can dove-tail this with the superset project, in that we get a Jenkins build on master of the superset directory where it publishes to our labs bucket.   should be possible with some token/key and maybe with the gsutil directly too?

**Comment by kordless** [comment]
On March 15th, this repository will no longer contain applications or projects related to Fusion. This issue will be affected and closed at that time. I will update here with the new repo address!

The buttons project, running https://streams.lucidworks.com/labs, will remain in this repository, along with the fastener VM system, which controls GCP for the project as a bastion box.

**Comment by sudosoup** [comment]
Closing, see comment above.
