### ISSUE TITLE
Make "searchhub" a button-ified app

### ISSUE THREAD

**Issue by erikhatcher** [lucidworks/streams#20]

**Comment by kordless** [comment]
App development task. Good start.

**Comment by kordless** [comment]
This is unlikely.

**Comment by kordless** [comment]
Sorry, scratch that. Maybe a great idea!

**Comment by erikhatcher** [comment]
it's possible!

**Comment by kordless** [comment]
Kicking to Connor.

**Comment by kordless** [comment]
On March 15th, this repository will no longer contain applications or projects related to Fusion. This issue will be affected and closed at that time. I will update here with the new repo address!

The buttons project, running https://streams.lucidworks.com/labs, will remain in this repository, along with the fastener VM system, which controls GCP for the project as a bastion box.

**Comment by sudosoup** [comment]
Closing, see comment above.

**Comment by sudosoup** [comment]
Closing, see comment above.
