### ISSUE TITLE
Add provisioning calls to start/provisioning scripts.

### ISSUE THREAD

**Issue by kordless** [lucidworks/streams#38]
The provisioning scripts need to be updated to do calls to Labs APIs to indicate current state of provisioning to the user, for a better user experience.

See #37

**Comment by kordless** [comment]
This would be from inside the buttons-start.sh script.

**Comment by kordless** [comment]
On March 15th, this repository will no longer contain applications or projects related to Fusion. This issue will be affected and closed at that time. I will update here with the new repo address!

The buttons project, running https://streams.lucidworks.com/labs, will remain in this repository, along with the fastener VM system, which controls GCP for the project as a bastion box.

**Comment by sudosoup** [comment]
Closing, see comment above.
