### ISSUE TITLE
Create UI style for Lou

### ISSUE THREAD

**Issue by kordless** [lucidworks/streams#39]
A new updated style may be considered for Lou.

**Comment by kordless** [comment]
.

**Comment by kordless** [comment]
On March 15th, this repository will no longer contain applications or projects related to Fusion. This issue will be affected and closed at that time. I will update here with the new repo address!

The buttons project, running https://streams.lucidworks.com/labs, will remain in this repository, along with the fastener VM system, which controls GCP for the project as a bastion box.

**Comment by sudosoup** [comment]
Closing, see comment above.
