### ISSUE TITLE
Create a raw Fusion stream

### ISSUE THREAD

**Issue by erikhatcher** [lucidworks/streams#42]
so that the quick start experience is available.

**Comment by kordless** [comment]
I think it's now pretty fast with hotstarts. I'll close for now.

**Comment by erikhatcher** [comment]
this is about making a stream template that doesn't install an app.    without an app, when fusion UI renders, it starts with a Quick Start screen.   with an app installed, it shows the app panels.

**Comment by kordless** [comment]
Sorry about closing that on you without asking. I'm going to assign this to @sudosoup.

**Comment by sudosoup** [comment]
this might be related: https://jira.lucidworks.com/browse/APOLLO-14309

Haven't been able to reproduce locally.

**Comment by erikhatcher** [comment]
So back to the original issue here - let's make a stream that is solely "just Fusion", so there's not going to be a .tar to grab and no buttons-start.sh to speak of (or could be an effectively empty one?)

**Comment by sudosoup** [comment]
I was testing with Training Labs template which has a blank buttons-start.sh script. I'll try spinning up one without the script to confirm.

**Comment by sudosoup** [comment]
Created a "vanilla" button which doesn't use a tarball. Still running into the issue, will do some more digging.

**Comment by kordless** [comment]
On March 15th, this repository will no longer contain applications or projects related to Fusion. This issue will be affected and closed at that time. I will update here with the new repo address!

The buttons project, running https://streams.lucidworks.com/labs, will remain in this repository, along with the fastener VM system, which controls GCP for the project as a bastion box.

**Comment by sudosoup** [comment]
Closing, see comment above.
