### ISSUE TITLE
Add Tracking

### ISSUE THREAD

**Issue by kordless** [lucidworks/streams#56]
We desire to know who is using /labs. Add tracking code for any tracking service here:

https://github.com/lucidworks/streams/blob/master/projects/buttons/web/handlers/instancehandlers.py#L585

At that point the user's email is set to the *email* variable.

**Comment by MarcusSorealheis** [comment]
I will try to get that in

except, we cannot send data like that Google Analytics
they will kick us off their platform
we need to use a different analytics product to capture things like that
most will allow it, but some will not
mainly Google Analytics

I can add another tracking service to the web app for tracking the web app specifically. I will look into that in the morning.

**Comment by kordless** [comment]
I'm going to close this ticket and open a new one to address the "broken" bits of using GA on the streams.lucidworks.com domain. We do not use the user's email address with GA and we already send it to Marketo so that it makes its way into Salesforce.

When someone figures out what other info we need about a user from their email address, let's open a ticket again to implement that service and add the tracking codes (if we need them).
