### ISSUE TITLE
Change Config File Values for Fusion Superset

### ISSUE THREAD

**Issue by MarcusSorealheis** [lucidworks/streams#59]
We could use `sed`, or we could pull the config files from our repo and simply do a `cp` of the entire `${FUSION_HOME}/conf/` dir.

The latter seems less painful, while the former more elegant. 

@erikhatcher @kordless what do you think?

**Comment by kordless** [comment]
This seems to be more of an app issue than a buttons/labs issue. Given we are still storing some application's data in this repo, I would suggest moving it out of here and then opening issues on those specific apps we are developing.

**Comment by kordless** [comment]
See #64. Once that is implemented, then we can close this issue and reopen one on the new superset/fusion app + a new issue here to address any configuration specific work that needs to be done on the startup scripts (different sized instances, custom actions like disable setting password, etc.)

**Comment by MarcusSorealheis** [comment]
Here is how I made the config changes for now, but perhaps there is a better way:

```
#   Configure Lucidworks Fusion to work in `binary` mode.
mkdir /patch_lab
mv /fusion/conf/hive-site.xml /patch_lab
pwd
cp /superset/fusion_conf/conf/hive-site_2.xml /patch_lab
cd /patch_lab
diff -u hive-site.xml hive-site_2.xml > hive-site.patch

patch < hive-site.patch

mv hive-site.xml /fusion/conf/
```
