### ISSUE TITLE
Build script for JRE installer to support upcoming versions

### ISSUE THREAD

**Issue by kordless** [lucidworks/streams#79]
Build script prompts for URL from Oracle page: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html (for reference only don't count on this working)

Output of script is two files which are uploaded to our "bucket" repo.

**Comment by MarcusSorealheis** [comment]
Given the changes in licensing and things like sign in required, can we consider using Open JDK?

**Comment by sudosoup** [comment]
Spoke with the product team and they confirmed using OpenJDK 8 for Fusion on testing/jenkins jobs.

**Comment by sudosoup** [comment]
71c722df - Implements install of open-jdk-8. Preliminary testing shows all fusion services spinning up successfully and webapp working normally.
